TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
vpath %.sym ..

# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += $(wildcard ../*.sym)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

